meta_product_name: "Flovelle"
meta_title: "Flovelle - Fresh Flowers, To Your Door, Every Week"
meta_description: "Select your seasonal flowers from our Dutch local flower farmers. Your carefully selected box of flowers will be deliverd on your doorstep, and for your convenience on your selected time. Get your first Flovelle Flowers now and support the Dutch local Flower Farmers!"
meta_image: "flovelle_cover_tint.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
